### ISSUE TITLE
MissingPluginException(No implementation found for method parse on channel flutter_libphonenumber)

### ISSUE THREAD

**Issue by kadishmal** [bottlepay/flutter_libphonenumber#12]
Hi,

I've followed the instructions in the README. Using:

```
Flutter 1.22.4
sdk: ">=2.7.0 <3.0.0"
flutter_libphonenumber: ^0.3.11
```

1. I have initialized the package via:

       FlutterLibphonenumber().init();

2. Then after the value is provided, I do:

       final res = await FlutterLibphonenumber().parse(value);

The last code throws the following exception:

    MissingPluginException(No implementation found for method parse on channel flutter_libphonenumber)

Any idea on what could be going wrong?

**Comment by kadishmal** [comment]
Apparently I haven't hard restarted the application which resulted in this issue. Even though the hot reload did work and picked up the changes, the new plugin/package didn't link/connect with iOS, thus causing this issue. Once restarted, it worked.

**Comment by acoutts** [comment]
Ah yup that makes sense. When you add a new package to your app, if it's just dart files, those are available as soon as you do a hot reload. But if the package includes ios/android native files, you need to do a fresh build again to bake those native frameworks into the app.
