### ISSUE TITLE
Example is not working as expected

### ISSUE THREAD

**Issue by monisnap-julien** [bottlepay/flutter_libphonenumber#14]
Hello,

I'm currently searching a library to handle the phone number changes in Ivory coast (details here: [link](https://www.rebtel.com/en/help/article/360018567259-numbering-plan-change-for-ivory-coast/) ).

I'm trying to test this library by running the example and see if everything is working as expected and unfortunately it's not. The test I'm running is the following :

```dart
import "package:test/test.dart";
import 'package:flutter_libphonenumber/flutter_libphonenumber.dart';

void main() {
  group('flutter_libphonenumber library testing', () {
    setUpAll(() async {
      await FlutterLibphonenumber().init();
    });

    test(
      'should parse phonenumber',
      () {
        final rawNumber = '+14145556666';
        final formattedNumber =
            FlutterLibphonenumber().formatNumberSync(rawNumber);

        expect(formattedNumber, "+1 414-555-6666");
      },
    );
  });
}
```

And the output is the following :

```
Expected: '+1 414-555-6666'
  Actual: '14145556666'
   Which: is different.
          Expected: +1 414-555 ...
            Actual: 1414555666 ...
                    ^
           Differ at offset 0
```

Is this a bug or am I doing something wrong ? Thank you in advance for the help !

**Comment by acoutts** [comment]
Yea this won't work because there is no platform running LibPhoneNumber for the plugin to load the countries data (with the regex patterns). You need to mock the behavior of native code like this in unit tests using something like mockito.

**Comment by monisnap-julien** [comment]
Thank you for the quick answer. I've achieved to run an integration test as follows and it's working as expected now :

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:flutter_libphonenumber/flutter_libphonenumber.dart';

import 'package:my_app/main.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    setUpAll(() async {
      await FlutterLibphonenumber().init();
    });

    testWidgets(
      'should parse phonenumber',
      (tester) async {
        app.main();
        await tester.pumpAndSettle();

        final rawNumber = '+14145556666';
        final formattedNumber =
            FlutterLibphonenumber().formatNumberSync(rawNumber);

        expect(formattedNumber, "+1 414-555-6666");
      },
    );
  });
}
```

However for Ivory Coast I ran this test and it didn't work :

```dart
testWidgets(
  'should parse new ivory coast phone numbers',
  (tester) async {
    app.main();
    await tester.pumpAndSettle();

    final rawNumber = '+2250767038865';
    final formattedNumber =
        FlutterLibphonenumber().formatNumberSync(rawNumber);

    expect(formattedNumber, "+225 07 67 03 88 65");
  },
);
```

And the error is : 

```
The following TestFailure object was thrown running a test:
  Expected: '+225 07 67 03 88 65'
  Actual: '+225 07 67 03 88'
   Which: is different. Both strings start the same, but the actual value is missing the following
trailing characters:  65
```

Should I open another issue for this specific case ?

**Comment by acoutts** [comment]
In this case you need to provide it the country region so it knows the pattern. It's probably a case that there are other +225 country numbers but have a different pattern.

**Comment by monisnap-julien** [comment]
I'm closing this issue because I was able to test the library. I open another issue about the Ivory Coast topic. Thanks for the help ! :)
