### ISSUE TITLE
Underlying Android and iOS need to be updated

### ISSUE THREAD

**Issue by monisnap-julien** [bottlepay/flutter_libphonenumber#15]
Hello,

There was some phone number changes in multiple countries (especially Ivory Coast). On Android side for example this is the [commit updating the metadata](https://github.com/google/libphonenumber/commit/619200d3b79553212faea4a2b12171c4c5050574).

Could you please update this library to use the latest Android and iOS libraries please ? :)

**Comment by acoutts** [comment]
I just published `0.3.12` / `1.0.2-nullsafety`. Please try those out and let me know if it works 👍

**Comment by monisnap-julien** [comment]
Thank you ! I've just tested for Ivory Coast and it's working.
