### ISSUE TITLE
Why deviceLocaleCountryCode is gone?

### ISSUE THREAD

**Issue by julienlebren** [bottlepay/flutter_libphonenumber#16]
I was using **CountryManager().deviceLocaleCountryCode**, but since I moved to 1.x to enable null safety, this var does not exist anymore. Why? It's was useful for selecting the default country of the user.

**Comment by KakkadDarshak** [comment]
Please tell me, any update on this?

**Comment by julienlebren** [comment]
No, so now I use this code:

```dart
import 'dart:ui' as ui;

ui.window.locale.countryCode
```

**Comment by acoutts** [comment]
I removed it as it didn't make sense to add another package dependency just to get the locale as it might limit some users.
