### ISSUE TITLE
LibPhonenumberTextFormatter multiple country codes

### ISSUE THREAD

**Issue by polivmi1** [bottlepay/flutter_libphonenumber#2]
When LibPhonenumberTextFormatter is used and for example +1 entered, it will detect Puerto Rico as a country. Canada and United States have the same.

It would be useful to get these based on area code: https://stackoverflow.com/questions/34404231/google-libphone-number-for-getting-country-name-for-the-same-country-code 

Is it possible to add a callback, when the full mask is matched? So that we could have an error state till it is a full number?

**Comment by acoutts** [comment]
I think we are stuck here. As per that issue, they never did add the functionality to PhoneNumberKit matching libphonenumber. There are a few open issues related to it as well: https://github.com/marmelroy/PhoneNumberKit/issues/135

I think it's safest to just have the user input their country, and use the formatter using the right country code.
