### ISSUE TITLE
isValidPhoneNumber true for invalid numbers.

### ISSUE THREAD

**Issue by JoshanTandukar** [bottlepay/flutter_libphonenumber#36]
+9779861eeeeee this number seems sure invalid. However, if passed to ,
  await PhoneNumberUtil.isValidPhoneNumber(
          phoneNumber: phone,
          isoCode: selectedCountryCode.code!,
        );
        
        is return true because the length exactly matches. Thank you for the package though.

**Comment by martipello** [comment]
isValidPhoneNumber is from the lib phone number package i can't see that its in this flutter_libphonenumber package, however I'd appreciate it being moved into this package so we can migrate fully from that to this

**Comment by acoutts** [comment]
@martipello you can do the same by calling `parse` and if you get a null result then it's not a valid number, if it is valid it would return the country info associated with it.

**Comment by martipello** [comment]
> @martipello you can do the same by calling `parse` and if you get a null result then it's not a valid number, if it is valid it would return the country info associated with it.

Very cool I will do just that, many thanks

**Comment by martipello** [comment]
it cant return null do you mean if it throws?

**Comment by acoutts** [comment]
sorry you're right, but that's correct. just check the error when you pass a bad number to it and catch that accordingly.
