### ISSUE TITLE
Phone number is truncated

### ISSUE THREAD

**Issue by Adam-Langley** [bottlepay/flutter_libphonenumber#4]
Formatting the number "+642101234567" using "formatNumberSync" produces the output "+64 21 012 3456"

It should not drop any digits from the end. The expected output is

"+64 21 012 34567"

Testing using libphonenumber.appspot produces the correct output:

[https://libphonenumber.appspot.com/phonenumberparser?number=%2B642101234567](https://libphonenumber.appspot.com/phonenumberparser?number=%2B642101234567)

**Comment by emmaxCreative** [comment]
I have the same problem with austrian numbers... were you able to solve this or is this still an issue ?

**Comment by acoutts** [comment]
This seems to work as expected as long as you select `Mobile` and `National` for this number:

Before formatting:
<img width="380" alt="Screen Shot 2020-10-25 at 11 25 37 AM" src="https://user-images.githubusercontent.com/9597207/97111396-d21d6c00-16b4-11eb-9ada-b8302014d2b3.png">

After formatting (sync):
<img width="415" alt="Screen Shot 2020-10-25 at 11 25 58 AM" src="https://user-images.githubusercontent.com/9597207/97111403-dc3f6a80-16b4-11eb-9237-a603b1f66951.png">

Clicking parse after also
<img width="394" alt="Screen Shot 2020-10-25 at 11 26 28 AM" src="https://user-images.githubusercontent.com/9597207/97111408-ed887700-16b4-11eb-8e3c-a15acd2d0de5.png">
 confirms it's correct:

**Comment by acoutts** [comment]
When using the synchronous formatting it's based on the example numbers supplied from libphonenumber, and uses a mask from those numbers. That's why it's important to specify the `mobile/fixe line` and `national/international` settings correctly so it uses the right mask to format it.

**Comment by acoutts** [comment]
```
[CountryWithPhoneCode(
  countryName: New Zealand,
  regionCode: NZ, 
  phoneCode: 64, 
  exampleNumberMobileNational: 021 123 4567, 
  exampleNumberFixedLineNational: 03-234 5678, 
  phoneMaskMobileNational: 000 000 0000, 
  phoneMaskFixedLineNational: 00-000 0000, 
  exampleNumberMobileInternational: +64 21 123 4567, 
  exampleNumberFixedLineInternational: +64 3-234 5678, 
  phoneMaskMobileInternational: +00 00 000 0000, 
  phoneMaskFixedLineInternational: +00 0-000 0000)
]
```

**Comment by emmaxCreative** [comment]
@acoutts  the problem is not that the number is not marked as valid but that the `LibPhonenumberTextFormatter` stops the textfield from entering the last number.

Whenever I parse the number +43 664 1234100 it returns it as valid number
But when I try to enter this number in a textfield with the inputFormatter set then the last digit cant be typed because the input is limited. So my guess is that the lenght limit is wrong ? I know it is a mobile number and i use the mobile mask for it.

**Comment by acoutts** [comment]
@emmaxCreative I moved your comment back to your issue to keep it on track with the Austrian number discussion 👍
