### ISSUE TITLE
Maintain package propose

### ISSUE THREAD

**Issue by deandreamatias** [bottlepay/flutter_libphonenumber#44]
Hi!
I'm a main contributor of [flutter-form-builder-ecosystem](https://github.com/flutter-form-builder-ecosystem) that currently include the package [phone_number](https://github.com/flutter-form-builder-ecosystem/phone_number).
I really want improve the maintain of phone_number, but is too hard to me alone.

We can join efforts to made a nice package to format, validate and other things with phone numbers. Take a look on this comment to more details https://github.com/natintosh/intl_phone_number_input/discussions/201#discussioncomment-5743946

Best regards

**Comment by acoutts-nydig** [comment]
Hi. I'm not sure what you're proposing we change. Is there anything specific you had in mind?

**Comment by acoutts** [comment]
I would say this package is already pretty mature, I would rather not merge it into anything else at this time. If you see a deficiency, I am always open to PRs to improve it.
