### ISSUE TITLE
Cant install pod

### ISSUE THREAD

**Issue by tungakanui** [bottlepay/flutter_libphonenumber#46]
[!] CocoaPods could not find compatible versions for pod "PhoneNumberKit/PhoneNumberKitCore":
  In Podfile:
    PhoneNumberKit (from `https://github.com/marmelroy/PhoneNumberKit`) was resolved to 3.5.10, which depends on
      PhoneNumberKit/PhoneNumberKitCore (= 3.5.10)

    flutter_libphonenumber_ios (from `.symlinks/plugins/flutter_libphonenumber_ios/ios`) was resolved to 1.1.0, which depends on
      PhoneNumberKit/PhoneNumberKitCore (= 3.5.9)

Specs satisfying the `PhoneNumberKit/PhoneNumberKitCore (= 3.5.10), PhoneNumberKit/PhoneNumberKitCore (= 3.5.9)` dependency were found, but they required a higher minimum deployment target.

**Comment by tungakanui** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3.1 22E772610a darwin-arm64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by acoutts-nydig** [comment]
Nice find - someone else reported a bug on it here: https://github.com/marmelroy/PhoneNumberKit/issues/643

It seems to have broken because we're depending on 3.5.9 and they pushed 3.5.10 overnight. I just published version 2.1.3 with the updated dependency so it works again.

You might have to `pod update` after adding the latest pub version.

**Comment by rbarzel** [comment]
Doh! No I didn't and that indeed solved it. Sorry for the churn. Thanks!

**Comment by rbarzel** [comment]
@acoutts-nydig do you have any guidance on how to use both `flutter_libphonenumber` and [phone_number](https://pub.dev/packages/phone_number) in the same app? They seen to depend on different versions of PhoneNumberKitCore...  Thank you

**Comment by acoutts** [comment]
No unfortunately you’ll have to pick one or the other or try and force the app to use one version of the pod. Maybe you can add the pod to your podfile to override it

**Comment by DevTeamJML** [comment]
> @rbarzel did you add the podfile entry as well from the readme?

where can I find the podfile entry from readme that u mentioned? I only found this flutter pub run melos bootstrap.
