### ISSUE TITLE
Unable to pod update

### ISSUE THREAD

**Issue by MingSern** [bottlepay/flutter_libphonenumber#48]
### Flutter doctor
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4 22F66 darwin-arm64, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

### Package version
```yaml
flutter_libphonenumber: ^2.1.3
```

### Expected
- able to run `pod update` without error

### Actual
- error shows up after running `pod update`
```bash
Specs satisfying the `PhoneNumberKit/PhoneNumberKitCore (= 3.6.0), 
PhoneNumberKit/PhoneNumberKitCore (= 3.5.10)` dependency were found, 
but they required a higher minimum deployment target.
```

**Comment by acoutts-nydig** [comment]
Make sure you added the entry to your podfile like the readme outlines.

**Comment by MingSern** [comment]
@acoutts-nydig So we need to install melos and bootstrap?

**Comment by MingSern** [comment]
I'll just put a tag for now.
```ruby
pod "PhoneNumberKit", :git => "https://github.com/marmelroy/PhoneNumberKit", :tag => "3.5.10"
```

**Comment by icodelifee** [comment]
> I'll just put a tag for now.
> 
> ```ruby
> pod "PhoneNumberKit", :git => "https://github.com/marmelroy/PhoneNumberKit", :tag => "3.5.10"
> ```

but this isnt working
```

  [!] CocoaPods could not find compatible versions for pod "PhoneNumberKit/PhoneNumberKitCore":
      In Podfile:
        PhoneNumberKit (from `https://github.com/marmelroy/PhoneNumberKit`, tag `3.5.10`) was resolved to 3.5.10, which depends on
          PhoneNumberKit/PhoneNumberKitCore (= 3.5.10)

        flutter_libphonenumber_ios (from `.symlinks/plugins/flutter_libphonenumber_ios/ios`) was resolved to 1.1.0, which depends on
          PhoneNumberKit/PhoneNumberKitCore (= 3.6.0)

    Specs satisfying the `PhoneNumberKit/PhoneNumberKitCore (= 3.6.0), PhoneNumberKit/PhoneNumberKitCore (= 3.5.10)` dependency were found, but they required a higher minimum deployment target.
```
Im getting the same error even after putting the tag

**Comment by icodelifee** [comment]
> can you please try the latest version just published?

Im on   `flutter_libphonenumber: ^2.1.4`

**Comment by icodelifee** [comment]
> Did you try pod update?

issue happens when i run pod update.
Im using codemagic for building.

**Comment by icodelifee** [comment]
is there a way i can downgrade @acoutts ?

**Comment by acoutts** [comment]
this is odd, i was able to upgrade and use the latest version with the example app.. is it an environment issue in codemagic?

**Comment by icodelifee** [comment]
Im sure that codemagic pulls all the deps and runs pod install everytime i run the build

**Comment by icodelifee** [comment]
Can it be an issue with Podfile.lock?

**Comment by icodelifee** [comment]
ill prolly get my macbook back tommorow, until then if there is way to downgrade and use it would be awesome

**Comment by acoutts** [comment]
I'm not sure on your codemagic setup, but doing a pod update should update the lock file and work after that. Are you able to reproduce the issue with the example app? Then you can narrow down is it an issue with this package, your project, or codemagic.

**Comment by icodelifee** [comment]
let me fork and check

**Comment by acoutts** [comment]
check the git tags to see, it will be there

**Comment by BenevidesLecontes** [comment]
@acoutts  what's the solution for this issue? I'm having this issue too

**Comment by MingSern** [comment]
@BenevidesLecontes @icodelifee For whoever that is still facing this issue, it's probably because of the dependency's version. Since the error says `which depends on PhoneNumberKit/PhoneNumberKitCore (= 3.6.0)`.
In your `Podfile`, your need to change the version tag to be `3.6.0` as such
```ruby
pod "PhoneNumberKit", :git => "https://github.com/marmelroy/PhoneNumberKit", :tag => "3.6.0" # here
```

**Comment by BenevidesLecontes** [comment]
hi @MingSern thank you, I already did that and is working,  @acoutts i think this not the best solution this issue needs to remain open until a better solution. In our company we are developing plugins that depend on this plugin, but everyone who uses our plugins has to configure this in the podfile.
