### ISSUE TITLE
Error while running in iOS with the latest flutter SDK 1.22.1

### ISSUE THREAD

**Issue by bharathiselvan** [bottlepay/flutter_libphonenumber#9]
Getting the below error in iOS

error: compiling for iOS 8.0, but module 'PhoneNumberKit' has a minimum deployment target of iOS 9.0: .....PhoneNumberKit/PhoneNumberKit.framework/Modules/PhoneNumberKit.swiftmodule/arm64-apple-ios.swiftmodule
    import PhoneNumberKit
           ^

**Comment by acoutts** [comment]
You need to update your app for iOS 9.0 minimum. This was a recent change in flutter and is now the minimum supported version.

**Comment by acoutts** [comment]
https://github.com/flutter/flutter/issues/58200#issuecomment-677709555

**Comment by bharathiselvan** [comment]
Thanks for the quick response.. 
But this doesn't solve my problem..
I am facing this issue even with a new project... In my old project, other flutter packages are working without any issues and when i add this package, i am getting the issue..

**Comment by acoutts** [comment]
The error `error: compiling for iOS 8.0` means your project is targeting iOS 8.0 though. Are you using the latest Xcode? You can no longer select 8.0 in the latest Xcode.

**Comment by bharathiselvan** [comment]
I downloaded the package source code and set the platform version of the package to 9.0 and it got fixed.
Updated  s.platform = :ios, "8.0" to  s.platform = :ios, "9.0" in flutter_libphonenumber.podspec file

**Comment by acoutts** [comment]
Ah I see now you're right! ok let me patch it.

**Comment by bharathiselvan** [comment]
okay.. thanks..

**Comment by acoutts** [comment]
Just published 0.3.11 to fix this.
